### ISSUE TITLE
Increase the delay before inactivity kick

### ISSUE THREAD

**Issue by lukky513** [zatikon/zatikon#14]
Relevant code is in SeverJanitor.java. 6 hours could be alright at the time.

It could be a good idea to refactor the code a bit, so it's more clear what is the logic, and in turn, make it configurable.

**Comment by IamFives** [comment]
I believe I have finished this task. I have 2 versions one where the only change is the inactivilty timer changed from one minute to 6 hours and one where the code has been refactored and time added. How do I go about sending this for approval?

**Comment by lukky513** [comment]
Happy to see a new contributor!
Please create a PR with the refactored version, I'm sure we can work out the details there.

**Comment by IamFives** [comment]
I will once I learn how to do that!

**Comment by lukky513** [comment]
We currently have a development channel on Discord - you can join us there to get any help you need! Here: https://discord.com/channels/1125418794475593768/1175471344071229440

**Comment by Ravean** [comment]
Finished in 1.1.5
