### ISSUE TITLE
Zealot relic ability has no range limit

### ISSUE THREAD

**Issue by Ravean** [zatikon/zatikon#15]
Should a unit with the Zealot relic switch places without any range limit when attacking. Currently this is the case and while only the AI starts with the relic it can be picked up and used. Things get weird when something with a 4 or more range use it. Definitely not a big deal as it is only in AI games and pretty uncommon, so very low priority.

**Comment by lukky513** [comment]
I think it's a bug. I hope it's an easy fix, given that the other relics generally work correctly already.

**Comment by Ravean** [comment]
What should the range limit be then? 2?

**Comment by lukky513** [comment]
I misunderstood the initial description as meaning it is the deployment distance, for some reason :)

I think 2 would be a bit short - maybe 3? Any cases that you found particularly weird or overpowered?
I'm mostly considering that units with long range usually have a low action limit.

**Comment by Ravean** [comment]
The relic is based on the fanatic unit (it is the only unit in the game with that power) and that is pretty good, with longer I think it is overpowered. For example an archer which has 2 actions could target a unit 4 spaces away and then another one 4 more spaces. Probably the best solution is for the AI not to give those relics to units with more range than 2 and units with more range than 2 not be able to pick them up.

**Comment by Ravean** [comment]
Completed in 1.1.5
