### ISSUE TITLE
Interface is covered by title bar in Linux (Ubuntu 22.02 GNOME)

### ISSUE THREAD

**Issue by Ravean** [zatikon/zatikon#3]
Interface is covered by title bar:
![image](https://github.com/zatikon/zatikon/assets/11357438/f5ca2cb6-5fed-443a-aa54-02af59fb5db9)

These options fix the problem.
flatpak run com.chroniclogic.Zatikon -Dpatch.extraHeight=10 -Dpatch.insetTop=10

**Comment by lukky513** [comment]
Does it happen for you in any of the other dialogs? Like login/create account?

**Comment by Ravean** [comment]
No it only seems to be on the window, the other windows are fine.

**Comment by Ravean** [comment]
These seems to be fixed now. Not sure if it is because of an update to Ubuntu, switching to Wayland or some other reason.
