### ISSUE TITLE
Forbid certain AI-specific configurations of units

### ISSUE THREAD

**Issue by lukky513** [zatikon/zatikon#42]
As it stands, because of unique abilities of AI, such as special powerups and no castle-cost ceiling, AI can be a bit too powerful in random moments.

The combos that were identified so far that we would like to prevent (thanks @Ravean):
- more than one Feathered Serpent
- Ruthless Warlock

A good solution here would be something that's easy to extend with extra cases, especially as we might make AI able to use more types of units than before.

**Comment by Ravean** [comment]
These rules are currently in the RelicPowerUp.java file.

**Comment by Ravean** [comment]
Completed in 1.1.5
